### ISSUE TITLE
iOS - linking

### ISSUE THREAD

**Issue by mtoninelli** [franroberti95/react-native-aws-freertos#1]
Thank you for sharing this module.

```
"react": "17.0.1",
"react-native": "0.64.0",
"react-native-aws-freertos": "^0.1.11"
```

The issue is on iOS running `pod install`.
Should we use a manual linking for this module? If yes how?

```
[!] CocoaPods could not find compatible versions for pod "react-native-aws-freertos":
  In Podfile:
    react-native-aws-freertos (from `../node_modules/react-native-aws-freertos`)

Specs satisfying the `react-native-aws-freertos (from `../node_modules/react-native-aws-freertos`)` dependency were found, but they required a higher minimum deployment target.
```

Thank you in advance.

**Comment by franroberti95** [comment]
Hi there!
Yes, you should manually link it. Adding the following code in your podfile:

  use_frameworks! :linkage => :static
  pod 'AmazonFreeRTOS'
  pod 'AWSAuthUI'
  pod 'AWSMobileClient','~> 2.17.0'
  pod 'AWSUserPoolsSignIn'
  pod 'react-native-aws-freertos', :path => '../node_modules/react-native-aws-freertos'

**Comment by mtoninelli** [comment]
Hi, thank you for your quick reply.

Here is what I've done:

- init new RN project (0.64.0)
- installed the module
- in pod file: added the links and increased the platform to 11 `platform :ios, '11.0'`
- commented `use_flipper!()`

Xcode gives this error

```
#import <FBDefines/FBDefines.h> ('FBDefines/FBDefines.h' file not found)
```

Am I missing something?

**Comment by franroberti95** [comment]
are you able to open the app under /example ? Im currently working on it, but so at least you can run it.
Its working for me with those steps.
try:
 in xcode: product -> clean build folder,
 delete Pods directory and do pod install

**Comment by mtoninelli** [comment]
Not able to open it under /example. I've done: 

- npm install
- cd ios && pod install
- in xcode: product -> clean build folder
- delete Pods directory and do pod install

Error:

`/Users/m/Documents/react-native-aws-freertos-master/example/ios/Pods/Target Support Files/Pods-AwsFreertosExample/Pods-AwsFreertosExample.debug.xcconfig: unable to open file (in target "AwsFreertosExample" in project "AwsFreertosExample")`

**Comment by franroberti95** [comment]
Let me paste every step just to make sure:
npm install
cd example && npm install
cd ios && pod pod install
then on xcode open /example/AwsFreertosExample.xcworkspace
run on device

**Comment by mtoninelli** [comment]
Thank you for updating the readme.

Yes, exactly the steps are those. Same issue... :/

This happens on:
RN 0.64.0
Xcode 12.3

I've also been sure to have cleaned the pod cache before.

**Comment by franroberti95** [comment]
Maybe try:
https://stackoverflow.com/questions/55558984/xcode-pods-projectname-debug-xcconfig-unable-to-open-file-wrong-directory

**Comment by franroberti95** [comment]
pod install should be done under /example/ios/ only

**Comment by mtoninelli** [comment]
I've also cleaned the pod cache in depth like this (yes in /example/ios/)  

pod cache clean --all
pod deintegrate 
pod install

**Comment by mtoninelli** [comment]
Managed to build it, was only some npm cache... It runs on ios too now.

It still shows this error before. Does the same on your machine?

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-aws-freertos (to unlink run: "react-native unlink react-native-aws-freertos")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

**Comment by franroberti95** [comment]
Cool. Yeah, i have to fix that warning. Also, ill update the demo app soon,
the current one was just for testing the lib was working
