### ISSUE TITLE
Having issues building iOS example project in this repo

### ISSUE THREAD

**Issue by mohammadfarooqi** [franroberti95/react-native-aws-freertos#11]
Hi!

I was having issues building the "example" project in iOS. I was successfully able to build the Android one. 

I am wondering if you can provide any steps we need to take or build instructions for the iOS, ie any target ios version or anything special we need to do using Xcode to run the example project.

Any assistance would be helpful. 

Thanks!

**Comment by mtoninelli** [comment]
Hi, what is the issue that you have?
