### ISSUE TITLE
DID_LIST_NETWORK not working on iphone6 (ios 12.5.1)

### ISSUE THREAD

**Issue by mtoninelli** [franroberti95/react-native-aws-freertos#2]
Hi Franco,

I've the library working perfectly on Android. 
On ios, once getConnectedDeviceAvailableNetworks is triggered, there are no networks listed with the DID_LIST_NETWORK event.
I've tried also with the example in the repo and it doesn't read the networks.

Do you know what it could be?

react native 0.64.0
ios (on device) 12.5.1
iphone 6

Thanks in advance

**Comment by franroberti95** [comment]
Actually yes i know what it could be. Sometimes the "is connected" status on iOS goes in before actually beeing connected. Try checking the connection status with AwsFreertos.deviceIsConnected(macAddr) first to ensure the connection. Also it would be good to check if characteristics can be read before triggering the listNetworks.
Ex:
    Check connection:
```
             AwsFreertos.deviceIsConnected(macAddr).then(
              (r: boolean) => {
                if (r) {
                  console.log(
                    'Setting state to connected. Reading Characteristics to ensure connection.'
                  );
                  setIsConnected(true);
                }
              }
            );
```

then ensure characteristics are readable:

```
const readCharacteristicsEvent = eventEmitter.addListener(
      eventKeys.DID_READ_CHARACTERISTIC_FROM_SERVICE,
      (newCharacteristic: Characteristic | Characteristic[]) => {
        console.log('Reading characteristic: ', newCharacteristic);
        if (Array.isArray(newCharacteristic)) {
          newCharacteristic.forEach((char) =>
            addCharacteristicToStore(char, store)
          );
        } else {
          addCharacteristicToStore(newCharacteristic, store);
        }
      }
    );
```

once you have all characteristics, trigger the wifi scan. If you are already doing this, other thing that could work is to try forgetting the device connection in your iphone's bluetooth settings and try the process again.

**Comment by mtoninelli** [comment]
Thanks Franco, I've tried as you suggested.

The `deviceIsConnected` response is true and prints "Setting state to connected. Reading Characteristics to ensure connection" ... so after that I'm going to trigger:

```AwsFreertos.getGattCharacteristicsFromServer(device.macAddr, serviceUuidString);``` What should I put as serviceUuidString ?

I tried with 'ad3cee4a-c6d0-4b38-aed6-5459813c5847' as you used in your example and also tried with an empty string but doesn't work.

In the iphone's bluetooth settings there are no device saved.

Any ideas?
Thanks!!!

**Comment by franroberti95** [comment]
In serviceUuidString you have to place the uuid of the gatt server hosted by your device. I will add a function to discover available servers later.

**Comment by mtoninelli** [comment]
I update here the solution that worked using the version 0.1.16

- I avoid to use the getGattCharacteristicsFromServer
- used this function as you suggested.
```
AwsFreertos.getDeviceServices(store.deviceSelected.macAddr)
  .finally( () => {
    setTimeout(() => {
      AwsFreertos.getDeviceServices(store.deviceSelected.macAddr)
        .finally((r) => console.log(r));
    }, 5000);
  });
  ```
