### ISSUE TITLE
Event ERROR_SAVE_NETWORK not received on iOS

### ISSUE THREAD

**Issue by Mitchizuky** [franroberti95/react-native-aws-freertos#6]
In the event there is a problem with connecting to a selected wi-fi the ERROR_SAVE_NETWORK event is never received on an iOS device. 

The ERROR_SAVE_NETWORK works as expected on android.

**Comment by johntvogt** [comment]
👍  for this feature, support for this was added here:
https://github.com/aws/amazon-freertos-ble-ios-sdk/pull/22/files
